"""
Lookup tables for address normalization.
These tables contain standard abbreviations and keywords used in address parsing.
"""

# Direction lookup: maps full direction names to abbreviations
DIRECTION_LOOKUP = [
    {"name": "NORTH", "abbrev": "N"},
    {"name": "SOUTH", "abbrev": "S"},
    {"name": "EAST", "abbrev": "E"},
    {"name": "WEST", "abbrev": "W"},
    {"name": "NORTHEAST", "abbrev": "NE"},
    {"name": "NORTHWEST", "abbrev": "NW"},
    {"name": "SOUTHEAST", "abbrev": "SE"},
    {"name": "SOUTHWEST", "abbrev": "SW"},
    {"name": "N", "abbrev": "N"},
    {"name": "S", "abbrev": "S"},
    {"name": "E", "abbrev": "E"},
    {"name": "W", "abbrev": "W"},
    {"name": "NE", "abbrev": "NE"},
    {"name": "NW", "abbrev": "NW"},
    {"name": "SE", "abbrev": "SE"},
    {"name": "SW", "abbrev": "SW"},
]

# Street type lookup: maps full street type names to abbreviations
# is_hw indicates if this is a highway-type that can appear at start
STREET_TYPE_LOOKUP = [
    {"name": "ALLEY", "abbrev": "ALY", "is_hw": False},
    {"name": "AVENUE", "abbrev": "AVE", "is_hw": False},
    {"name": "BOULEVARD", "abbrev": "BLVD", "is_hw": False},
    {"name": "CIRCLE", "abbrev": "CIR", "is_hw": False},
    {"name": "COURT", "abbrev": "CT", "is_hw": False},
    {"name": "COVE", "abbrev": "CV", "is_hw": False},
    {"name": "CREEK", "abbrev": "CRK", "is_hw": False},
    {"name": "DRIVE", "abbrev": "DR", "is_hw": False},
    {"name": "EXPRESSWAY", "abbrev": "EXPY", "is_hw": True},
    {"name": "FREEWAY", "abbrev": "FWY", "is_hw": True},
    {"name": "HIGHWAY", "abbrev": "HWY", "is_hw": True},
    {"name": "LANE", "abbrev": "LN", "is_hw": False},
    {"name": "PARKWAY", "abbrev": "PKWY", "is_hw": False},
    {"name": "PLACE", "abbrev": "PL", "is_hw": False},
    {"name": "PLAZA", "abbrev": "PLZ", "is_hw": False},
    {"name": "POINT", "abbrev": "PT", "is_hw": False},
    {"name": "RIDGE", "abbrev": "RDG", "is_hw": False},
    {"name": "ROAD", "abbrev": "RD", "is_hw": False},
    {"name": "ROUTE", "abbrev": "RTE", "is_hw": True},
    {"name": "SQUARE", "abbrev": "SQ", "is_hw": False},
    {"name": "STREET", "abbrev": "ST", "is_hw": False},
    {"name": "TERRACE", "abbrev": "TER", "is_hw": False},
    {"name": "TRAIL", "abbrev": "TRL", "is_hw": False},
    {"name": "TURNPIKE", "abbrev": "TPKE", "is_hw": True},
    {"name": "WAY", "abbrev": "WAY", "is_hw": False},
    # Highway-related (these often come at the beginning)
    {"name": "INTERSTATE", "abbrev": "I", "is_hw": True},
    {"name": "STATE HIGHWAY", "abbrev": "SR", "is_hw": True},
    {"name": "STATE ROUTE", "abbrev": "SR", "is_hw": True},
    {"name": "US HIGHWAY", "abbrev": "US", "is_hw": True},
    {"name": "US ROUTE", "abbrev": "US", "is_hw": True},
    {"name": "COUNTY ROAD", "abbrev": "CR", "is_hw": True},
    # Common abbreviations
    {"name": "AVE", "abbrev": "AVE", "is_hw": False},
    {"name": "BLVD", "abbrev": "BLVD", "is_hw": False},
    {"name": "CIR", "abbrev": "CIR", "is_hw": False},
    {"name": "CT", "abbrev": "CT", "is_hw": False},
    {"name": "DR", "abbrev": "DR", "is_hw": False},
    {"name": "HWY", "abbrev": "HWY", "is_hw": True},
    {"name": "LN", "abbrev": "LN", "is_hw": False},
    {"name": "PKWY", "abbrev": "PKWY", "is_hw": False},
    {"name": "PL", "abbrev": "PL", "is_hw": False},
    {"name": "RD", "abbrev": "RD", "is_hw": False},
    {"name": "ST", "abbrev": "ST", "is_hw": False},
]

# Secondary unit lookup: apartment, suite, etc.
SECONDARY_UNIT_LOOKUP = [
    {"name": "APARTMENT", "abbrev": "APT"},
    {"name": "APT", "abbrev": "APT"},
    {"name": "BUILDING", "abbrev": "BLDG"},
    {"name": "BLDG", "abbrev": "BLDG"},
    {"name": "DEPARTMENT", "abbrev": "DEPT"},
    {"name": "DEPT", "abbrev": "DEPT"},
    {"name": "FLOOR", "abbrev": "FL"},
    {"name": "FL", "abbrev": "FL"},
    {"name": "FRONT", "abbrev": "FRNT"},
    {"name": "HANGER", "abbrev": "HNGR"},
    {"name": "KEY", "abbrev": "KEY"},
    {"name": "LOBBY", "abbrev": "LBBY"},
    {"name": "LOT", "abbrev": "LOT"},
    {"name": "LOWER", "abbrev": "LOWR"},
    {"name": "OFFICE", "abbrev": "OFC"},
    {"name": "OFC", "abbrev": "OFC"},
    {"name": "PENTHOUSE", "abbrev": "PH"},
    {"name": "PH", "abbrev": "PH"},
    {"name": "PIER", "abbrev": "PIER"},
    {"name": "REAR", "abbrev": "REAR"},
    {"name": "ROOM", "abbrev": "RM"},
    {"name": "RM", "abbrev": "RM"},
    {"name": "SIDE", "abbrev": "SIDE"},
    {"name": "SLIP", "abbrev": "SLIP"},
    {"name": "SPACE", "abbrev": "SPC"},
    {"name": "SPC", "abbrev": "SPC"},
    {"name": "STOP", "abbrev": "STOP"},
    {"name": "SUITE", "abbrev": "STE"},
    {"name": "STE", "abbrev": "STE"},
    {"name": "TRAILER", "abbrev": "TRLR"},
    {"name": "UNIT", "abbrev": "UNIT"},
    {"name": "UPPER", "abbrev": "UPPR"},
    {"name": "#", "abbrev": "#"},
]

# US State lookup: maps state names and common variations to abbreviations
STATE_LOOKUP = [
    {"name": "ALABAMA", "abbrev": "AL"},
    {"name": "ALASKA", "abbrev": "AK"},
    {"name": "ARIZONA", "abbrev": "AZ"},
    {"name": "ARKANSAS", "abbrev": "AR"},
    {"name": "CALIFORNIA", "abbrev": "CA"},
    {"name": "COLORADO", "abbrev": "CO"},
    {"name": "CONNECTICUT", "abbrev": "CT"},
    {"name": "DELAWARE", "abbrev": "DE"},
    {"name": "FLORIDA", "abbrev": "FL"},
    {"name": "GEORGIA", "abbrev": "GA"},
    {"name": "HAWAII", "abbrev": "HI"},
    {"name": "IDAHO", "abbrev": "ID"},
    {"name": "ILLINOIS", "abbrev": "IL"},
    {"name": "INDIANA", "abbrev": "IN"},
    {"name": "IOWA", "abbrev": "IA"},
    {"name": "KANSAS", "abbrev": "KS"},
    {"name": "KENTUCKY", "abbrev": "KY"},
    {"name": "LOUISIANA", "abbrev": "LA"},
    {"name": "MAINE", "abbrev": "ME"},
    {"name": "MARYLAND", "abbrev": "MD"},
    {"name": "MASSACHUSETTS", "abbrev": "MA"},
    {"name": "MICHIGAN", "abbrev": "MI"},
    {"name": "MINNESOTA", "abbrev": "MN"},
    {"name": "MISSISSIPPI", "abbrev": "MS"},
    {"name": "MISSOURI", "abbrev": "MO"},
    {"name": "MONTANA", "abbrev": "MT"},
    {"name": "NEBRASKA", "abbrev": "NE"},
    {"name": "NEVADA", "abbrev": "NV"},
    {"name": "NEW HAMPSHIRE", "abbrev": "NH"},
    {"name": "NEW JERSEY", "abbrev": "NJ"},
    {"name": "NEW MEXICO", "abbrev": "NM"},
    {"name": "NEW YORK", "abbrev": "NY"},
    {"name": "NORTH CAROLINA", "abbrev": "NC"},
    {"name": "NORTH DAKOTA", "abbrev": "ND"},
    {"name": "OHIO", "abbrev": "OH"},
    {"name": "OKLAHOMA", "abbrev": "OK"},
    {"name": "OREGON", "abbrev": "OR"},
    {"name": "PENNSYLVANIA", "abbrev": "PA"},
    {"name": "RHODE ISLAND", "abbrev": "RI"},
    {"name": "SOUTH CAROLINA", "abbrev": "SC"},
    {"name": "SOUTH DAKOTA", "abbrev": "SD"},
    {"name": "TENNESSEE", "abbrev": "TN"},
    {"name": "TEXAS", "abbrev": "TX"},
    {"name": "UTAH", "abbrev": "UT"},
    {"name": "VERMONT", "abbrev": "VT"},
    {"name": "VIRGINIA", "abbrev": "VA"},
    {"name": "WASHINGTON", "abbrev": "WA"},
    {"name": "WEST VIRGINIA", "abbrev": "WV"},
    {"name": "WISCONSIN", "abbrev": "WI"},
    {"name": "WYOMING", "abbrev": "WY"},
    # Territories
    {"name": "DISTRICT OF COLUMBIA", "abbrev": "DC"},
    {"name": "PUERTO RICO", "abbrev": "PR"},
    {"name": "VIRGIN ISLANDS", "abbrev": "VI"},
    {"name": "GUAM", "abbrev": "GU"},
    {"name": "AMERICAN SAMOA", "abbrev": "AS"},
    # Common abbreviations
    {"name": "AL", "abbrev": "AL"},
    {"name": "AK", "abbrev": "AK"},
    {"name": "AZ", "abbrev": "AZ"},
    {"name": "AR", "abbrev": "AR"},
    {"name": "CA", "abbrev": "CA"},
    {"name": "CO", "abbrev": "CO"},
    {"name": "CT", "abbrev": "CT"},
    {"name": "DE", "abbrev": "DE"},
    {"name": "FL", "abbrev": "FL"},
    {"name": "GA", "abbrev": "GA"},
    {"name": "HI", "abbrev": "HI"},
    {"name": "ID", "abbrev": "ID"},
    {"name": "IL", "abbrev": "IL"},
    {"name": "IN", "abbrev": "IN"},
    {"name": "IA", "abbrev": "IA"},
    {"name": "KS", "abbrev": "KS"},
    {"name": "KY", "abbrev": "KY"},
    {"name": "LA", "abbrev": "LA"},
    {"name": "ME", "abbrev": "ME"},
    {"name": "MD", "abbrev": "MD"},
    {"name": "MA", "abbrev": "MA"},
    {"name": "MI", "abbrev": "MI"},
    {"name": "MN", "abbrev": "MN"},
    {"name": "MS", "abbrev": "MS"},
    {"name": "MO", "abbrev": "MO"},
    {"name": "MT", "abbrev": "MT"},
    {"name": "NE", "abbrev": "NE"},
    {"name": "NV", "abbrev": "NV"},
    {"name": "NH", "abbrev": "NH"},
    {"name": "NJ", "abbrev": "NJ"},
    {"name": "NM", "abbrev": "NM"},
    {"name": "NY", "abbrev": "NY"},
    {"name": "NC", "abbrev": "NC"},
    {"name": "ND", "abbrev": "ND"},
    {"name": "OH", "abbrev": "OH"},
    {"name": "OK", "abbrev": "OK"},
    {"name": "OR", "abbrev": "OR"},
    {"name": "PA", "abbrev": "PA"},
    {"name": "RI", "abbrev": "RI"},
    {"name": "SC", "abbrev": "SC"},
    {"name": "SD", "abbrev": "SD"},
    {"name": "TN", "abbrev": "TN"},
    {"name": "TX", "abbrev": "TX"},
    {"name": "UT", "abbrev": "UT"},
    {"name": "VT", "abbrev": "VT"},
    {"name": "VA", "abbrev": "VA"},
    {"name": "WA", "abbrev": "WA"},
    {"name": "WV", "abbrev": "WV"},
    {"name": "WI", "abbrev": "WI"},
    {"name": "WY", "abbrev": "WY"},
    {"name": "DC", "abbrev": "DC"},
    {"name": "PR", "abbrev": "PR"},
    {"name": "VI", "abbrev": "VI"},
    {"name": "GU", "abbrev": "GU"},
    {"name": "AS", "abbrev": "AS"},
]
